### ISSUE TITLE
Módulo 1 - Banco de dados

### ISSUE THREAD

**Issue by lcsampaioo** [lopespt/TCC-MusicGenerator#1]
- [x] Montar ambiente para base de dados (Lakh MIDI)
- [x] Testes dos arquivos MIDI da base
- [x] Filtro por arquivos contendo letras de músicas
- [x] Remover duplicatas
- [x] Montar a estrutura do objeto contendo as informações dos arquivos MIDI
- [x] Exportar arquivo JSON contendo as informações dos arquivos MIDI
- [x] Exportar arquivos MIDI contendo letras musicais
- [x] Analizar trilhas para acordes e notas nos arquivo exportado @eliasputtini 
- [x] Filtrar acompanhamento da letra

**Comment by lopespt** [comment]
- Estratégia para acordes: As trilhas os acordes são baseadas nos instrumentos que tocam mais notas ao mesmo tempo. 
   Para saber o acorde, pegaremos as 3 notas mais baixas

- Estratégia para melogias: Escolher o instrumento que toca notas no mesmo tempo do texto. Pegaremos a nota mais aguda.
